FROM jboss/wildfly
MAINTAINER Alexander Schug <alexander.schug@jipp.it>



############################################
# Configure Copy War file into the deploment folder of Wildfly
############################################
//COPY SimpleJavaWebApp_war/SimpleJavaWebApp_war.war /opt/jboss/wildfly/standalone/deployments/




